// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251117145420_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("WebApplication1.Models.Stemmer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Alliansen")
                        .HasColumnType("integer")
                        .HasColumnName("alliansen");

                    b.Property<int>("Ap")
                        .HasColumnType("integer")
                        .HasColumnName("ap");

                    b.Property<int>("Demokratene")
                        .HasColumnType("integer")
                        .HasColumnName("demokratene");

                    b.Property<int>("Folkestyret")
                        .HasColumnType("integer")
                        .HasColumnName("folkestyret");

                    b.Property<int>("Frp")
                        .HasColumnType("integer")
                        .HasColumnName("frp");

                    b.Property<int>("Helsepartiet")
                        .HasColumnType("integer")
                        .HasColumnName("helsepartiet");

                    b.Property<int>("Hoyre")
                        .HasColumnType("integer")
                        .HasColumnName("hoyre");

                    b.Property<int>("Inp")
                        .HasColumnType("integer")
                        .HasColumnName("inp");

                    b.Property<string>("Kommune")
                        .HasColumnType("text")
                        .HasColumnName("kommune");

                    b.Property<int>("Krf")
                        .HasColumnType("integer")
                        .HasColumnName("krf");

                    b.Property<int>("Kystpartiet")
                        .HasColumnType("integer")
                        .HasColumnName("kystpartiet");

                    b.Property<int>("Liberalistene")
                        .HasColumnType("integer")
                        .HasColumnName("liberalistene");

                    b.Property<int>("Mdg")
                        .HasColumnType("integer")
                        .HasColumnName("mdg");

                    b.Property<int>("Nkp")
                        .HasColumnType("integer")
                        .HasColumnName("nkp");

                    b.Property<int>("NorskRepublikanskAllianse")
                        .HasColumnType("integer")
                        .HasColumnName("norsk_republikansk_allianse");

                    b.Property<int>("PartietSentrum")
                        .HasColumnType("integer")
                        .HasColumnName("partiet_sentrum");

                    b.Property<int>("Pdk")
                        .HasColumnType("integer")
                        .HasColumnName("pdk");

                    b.Property<int>("Pensjonistpartiet")
                        .HasColumnType("integer")
                        .HasColumnName("pensjonistpartiet");

                    b.Property<int>("Piratpartiet")
                        .HasColumnType("integer")
                        .HasColumnName("piratpartiet");

                    b.Property<int>("Rodt")
                        .HasColumnType("integer")
                        .HasColumnName("rodt");

                    b.Property<int>("Sp")
                        .HasColumnType("integer")
                        .HasColumnName("sp");

                    b.Property<int>("Sv")
                        .HasColumnType("integer")
                        .HasColumnName("sv");

                    b.Property<int>("Venstre")
                        .HasColumnType("integer")
                        .HasColumnName("venstre");

                    b.Property<int>("Verdipartiet")
                        .HasColumnType("integer")
                        .HasColumnName("verdipartiet");

                    b.HasKey("Id");

                    b.ToTable("stemmer", (string)null);
                });

            modelBuilder.Entity("WebApplication1.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .HasColumnType("text")
                        .HasColumnName("adresse");

                    b.Property<string>("BankIdUuid")
                        .HasColumnType("varchar(36)")
                        .HasColumnName("bankiduuid");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Firstname")
                        .HasColumnType("text")
                        .HasColumnName("firstname");

                    b.Property<string>("Fodselsnr")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("fodselsnr");

                    b.Property<bool?>("HasVoted")
                        .HasColumnType("boolean")
                        .HasColumnName("hasvoted");

                    b.Property<string>("Kommune")
                        .HasColumnType("text")
                        .HasColumnName("kommune");

                    b.Property<string>("Lastname")
                        .HasColumnType("text")
                        .HasColumnName("lastname");

                    b.Property<string>("Passord")
                        .HasColumnType("text")
                        .HasColumnName("passord");

                    b.Property<string>("Phonenr")
                        .HasColumnType("text")
                        .HasColumnName("phonenr");

                    b.Property<string>("Postnr")
                        .HasColumnType("text")
                        .HasColumnName("postnr");

                    b.Property<string>("Sex")
                        .HasColumnType("text")
                        .HasColumnName("sex");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
